language: node_js

node_js:
- stable

addons:
  apt:
    packages:
    - gcc
    - g++
    - libstdc++6
    - pulseaudio

cache:
  directories:
  - $HOME/.npm
  - node_modules

before_install:
- export CHROME_BIN=chromium-browser
- export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- pulseaudio --start

before_script:
- DEBUG=eslint:cli-engine npm run lint:all

deploy:
- provider: npm
  email: kirill.konshin@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    node: stable
    tags: true
    repo: ringcentral/ringcentral-web-phone
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - src/ringcentral-web-phone.js
  on:
    node: stable
    tags: true
    repo: ringcentral/ringcentral-web-phone

after_success:
- npm run test:coverage